mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',  auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('', views.TestPage.as_view(), name="test"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('',include('newspapers.urls', namespace="newspapers")),
    path('',include('rates.urls', namespace="rates")),
    #path('test/', views.TestPage.as_view(), name="test"),
    #path('newsletter/',include('newsletter.urls', namespace="newsletter")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rates/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='rates'

urlpatterns = [
	        path('news_ratess/<int:pk>/', views.news_ratess, name="news_ratess"),
	        path('news_rates/', views.news_rates, name="news_rates"),
	        path('city_rates/', views.city_rates, name="city_rates"),
	        path('paper_rates/<int:pk>/', views.paper_rates, name="paper_rates"),
	        path('calc/', views.calc, name="calc"),
            
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rates/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from newspapers.models import Newspaper_name,Preference

class News_rates(models.Model):
	newspaper_name=models.OneToOneField(Newspaper_name, on_delete=models.CASCADE)
	rate_text=models.TextField(null=True, blank=True)
	preferences=models.OneToOneField(Preference, on_delete=models.CASCADE)
class City(models.Model):
	city_text=models.TextField(null=True, blank=True)

rates/views.py
from django.shortcuts import render
from .models import *
from newspapers.models import Newspaper_name
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse ,HttpResponseRedirect

# Create your views here.

# class ViewListView(ListView):
# 	model = News_rates
# 	context_object_name = 'news_rates'

# class ViewDetailView(DetailView):
# 	model = News_rates
# 	context_object_name = 'news_rates_detail'
# 	template_name = 'newspapers/news_rates_detail.html'

def news_rates(request):
	if request.method == 'POST':
		quote = request.POST.get('name')
		if not(quote):
			p=News_rates.objects.all()
			page = request.GET.get('page', 1)
			paginator = Paginator(p, 1)
			try:
				rrates = paginator.page(page)
			except PageNotAnInteger:
				rrates = paginator.page(1)
			except EmptyPage:
				rrates = paginator.page(paginator.num_pages)
			context ={
			'newspapers':Newspaper_name.objects.all(),
			'news_rates':rrates
			}
		else:
			# quote=Newspaper_name.objects.filter(name=quote1)
			p=list(News_rates.objects.filter(newspaper_name_id=int(quote[-1])))
			#print(p.rate_text)
			page = request.GET.get('page', 1)
			paginator = Paginator(p, 1)
			try:
				rrates = paginator.page(page)
			except PageNotAnInteger:
				rrates = paginator.page(1)
			except EmptyPage:
				rrates = paginator.page(paginator.num_pages)
			context ={
			'newspapers':Newspaper_name.objects.all(),
			'news_rates':rrates
			}
	else:
		p=News_rates.objects.all()
		#print(p.rate_text)
		page = request.GET.get('page', 1)
		paginator = Paginator(p, 1)
		try:
			rrates = paginator.page(page)
		except PageNotAnInteger:
			rrates = paginator.page(1)
		except EmptyPage:
			rrates = paginator.page(paginator.num_pages)
		context ={
		'newspapers':Newspaper_name.objects.all(),
		'news_rates':rrates
		}

	# context={
	# 'newspapers':Newspaper_name.objects.all()
	# }

	return render(request, 'rates/news_rate_detail.html', context=context )

def news_ratess(request,pk):
	context ={
		'newspapers':Newspaper_name.objects.all(),
		'news_rates':list(News_rates.objects.filter(newspaper_name_id=int(pk)))
	}
	return render(request, 'rates/news_rate_detail.html', context=context )


def paper_rates(request,pk):

	name=str(City.objects.get(pk=pk).city_text)
	print(name)

	from bs4 import BeautifulSoup
	from urllib.request import urlopen

	url ='https://www.bhavesads.com/'+name+'-newspaper/display-ad-rates'

	source = urlopen(url)
	html_data = BeautifulSoup(source).find('div',class_='tab-content').find('div',{'id': 'Categorys'}).find_all('div', class_='col-sm-12')
	paper=[]
	for data in html_data:
		try:
			paper1 = data.find('p',class_='special-text').text[:-10]
			paper.append(paper1)
		except AttributeError:
			pass

	names=[]
	for p in paper:
		names.append(Newspaper_name.objects.get(name=p))

	return render(request, 'rates/paper-list.html',{'city':names})


def city_rates(request):
	return render(request, 'rates/city-list.html',{'city':City.objects.all()})

def calc(request):

	return render(request, 'rates/calculater.html', {})

rates/templates/rates/calculater.html
{% extends "main.html" %}
{% block content %}
<div class="container rounded">
	<iframe id="f" src="http://www.davp.nic.in/Upload/(S(itkbuj45a0uxsp45yfh0y3f5))/davp_estimate.aspx"></iframe>
</div>
<script type="text/javascript">
	$('#sidebar').hide();
	$("iframe").css({"width": "100%", "height": "1250px","border": "0px"});
</script>
{% endblock %}

rates/templates/rates/city-list.html
{% extends "main.html" %}
{% block content %}
<div class="container">
	<h3 class="text-center mb-2">List Of News Papers</h3>
	<br>
	<div class="row  mx-auto">
		{% for c in city %}
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c1" class="list-group text-center">
				<li class="my-2"><a href="{% url 'rates:paper_rates' pk=c.pk %}">{{c.city_text}}</a></li>
			</ul>
		</div>
		{% endfor %}
		<!-- <div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c2" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div>
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c3" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div>
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c4" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div> -->
	</div>
</div>
<!-- <script type="text/javascript">
	for (var i = 1; i <= 122; i++) {
		var c = parseInt(i/30) + 1 ;
		$('#c'+c).append('<li class="my-2">NewsPaper '+i+'</li>');
	}
	//$('c1,c2,c3,c4').css({"font-size":"30px"})
</script> -->

{% endblock %}

rates/templates/rates/news_rate_detail.html
{% extends "main.html" %}
{% block content %}

<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>
<div class="container mx-auto mb-4">
    <h5 class="text-center">Search For Rates</h5>
    <form class="form-inline" id='filter' action="{% url 'rates:news_rates' %}" name='filter'  method='post'>
        <div class="col-lg-3 mt-3">

                {% csrf_token %}
            <select class="form-control-sm bg-dark text-white col-12 border-success" id='name' name='name'>

                <option>Select</option>
                {% for opt in newspapers %}
                <option>{{opt.name}}  {{opt.pk}}</option>
                <!-- <option>2</option> -->
                {% endfor %}
            </select>
        </div>
        <div class="text-center" id="pp">
            <input class="btn btn-sm btn-success  col-12 mt-3" type="submit" name="" value="Search News">
        </div>
        <script type="text/javascript">
            if($(window).width()<596)
                $('#pp').addClass('mx-auto');
            console.log(5);
        </script>
    </form>
</div>

<!-- Table Section -->
<div class="">
    <div class="newspapercategory-table">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                   <h2>Check out<strong> {{news_rates.Newspaper_name.name}}</strong> Display  <strong>Ad Rates</strong></h2>
                    {% for opt in news_rates %}
                    {% autoescape off %}
                   {{opt.rate_text}}
                                       <!--Paginator-->
<!--Paginator-->
<div class="container">
    <div class="text-center">
  {% if news_rates.has_other_pages %}
      <ul class="pagination">
        {% if news_rates.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ news_rates.previous_page_number }} tabindex="-1"">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}
        {% for i in news_rates.paginator.page_range %}
          {% if news_rates.number == i %}
            <li class="page-item active "><span class="page-link">{{ i }} <span class="sr-only page-link">(current)</span></span></li>
          {% else %}
            <li class=" page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if news_rates.has_next %}
          <li class="page-item" ><a class="page-link" href="?page={{ news_rates.next_page_number }}" tabindex="-1">Next</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
</div>
                   {% endautoescape %}
                   {% endfor %}

                    <!-- <h2>Check out<strong> The Hindu</strong> Display  <strong>Ad Rates</strong></h2>
                    <p class="green-bg-para text-center">Tariff Rates in Rupees per Sq.cm. (w.e.f 1-05-2018)</p>
                    <div class="resp-table">
                        <table>
                            <thead>
                                <tr>
                                    <td>Edition</td>
                                    <td>Base</td>
                                    <td>Mon to Thus</td>
                                    <td>Fri &amp; Sat</td>
                                    <td>Sunday</td>
                                    <td>Front Page</td>
                                    <td>Page 3</td>
                                    <td>Back Page</td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Eastern Edition</td>
                                    <td></td>
                                    <td>220</td>
                                    <td>240</td>
                                    <td>230</td>
                                    <td>60</td>
                                    <td></td>
                                    <td></td>
                                </tr>

                            </tbody>
                        </table> -->
                </div>
            </div>
        </div>
    </div>
</div>




<script type="text/javascript">
    $('table').addClass('table table-striped bg-white text-dark shadow border rounded bg-success ');
    $('h2').addClass('text-center');
    $('table thead tr td').addClass('text-white mt-1 bg-secondary');
</script>

<!-- <script type="text/javascript">
    for(var i=0;i<20;i++)
    $('tbody').append('<tr><td>Eastern Edition</td><td></td><td>220</td><td>240</td><td>230</td><td>60</td><td></td><td></td></tr>');
</script> -->

{% endblock %}

rates/templates/rates/news_rate_detail0.html
{% extends "main.html" %}
{% block content %}

<!-- Table Section -->        
<div class="">
    <div class="newspapercategory-table">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    {{news_rates.rate_text}}
                   <!-- text wala part
                   <p class="green-bg-para text-center">Tariff Rates in Rupees per Sq.cm. (w.e.f 1-05-2018)</p>
                    <table>
<thead>
<tr class=""tableizer-firstrow"">
<th>Edition</th>
<th>Inner Page (B/W)</th>
<th>Inner Page (Colour)</th>
<th>Front Page (B/W)</th>
<th>Front Page (Colour)</th>
<th>Back Page (B/W)</th>
<th>Back Page (Colour)</th>
</tr>
</thead>
<tbody>
<tr>
<td>Varanasi</td>
<td>540</td>
<td>1080</td>
<td>1080</td>
<td>2700</td>
<td>810</td>
<td>2160</td>
</tr>
<tr>
<td>Allahabad</td>
<td>270</td>
<td>540</td>
<td>540</td>
<td>1350</td>
<td>405</td>
<td>1080</td>
</tr>
<tr>
<td>Gorakpur</td>
<td>270</td>
<td>540</td>
<td>540</td>
<td>1350</td>
<td>405</td>
<td>1080</td>
</tr>
<tr>
<td>Kanpur</td>
<td>540</td>
<td>1080</td>
<td>1080</td>
<td>2700</td>
<td>810</td>
<td>2160</td>
</tr>
<tr>
<td>Lucknow</td>
<td>360</td>
<td>720</td>
<td>720</td>
<td>1800</td>
<td>540</td>
<td>1440</td>
</tr>
<tr>
<td>Agra</td>
<td>315</td>
<td>630</td>
<td>630</td>
<td>1575</td>
<td>473</td>
<td>1260</td>
</tr>
<tr>
<td>Bareily</td>
<td>270</td>
<td>540</td>
<td>540</td>
<td>1350</td>
<td>405</td>
<td>1080</td>
</tr>
<tr>
<td>Haldwani (Uttarkhand)</td>
<td>180</td>
<td>360</td>
<td>360</td>
<td>900</td>
<td>270</td>
<td>720</td>
</tr>
<tr>
<td>Patna</td>
<td>540</td>
<td>1080</td>
<td>1080</td>
<td>2700</td>
<td>810</td>
<td>2160</td>
</tr>
<tr>
<td>Ranchi (Dhanbad)</td>
<td>360</td>
<td>720</td>
<td>720</td>
<td>1800</td>
<td>540</td>
<td>1440</td>
</tr>
<tr>
<td>Jamshedpur</td>
<td>270</td>
<td>540</td>
<td>540</td>
<td>1350</td>
<td>405</td>
<td>1080</td>
</tr>
<tr>
<td>All Edition</td>
<td>1710</td>
<td>3420</td>
<td>3420</td>
<td>8550</td>
<td>2565</td>
<td>6840</td>
</tr>
<tr>
<td>UP Edition</td>
<td>1350</td>
<td>2700</td>
<td>2700</td>
<td>6750</td>
<td>2025</td>
<td>5400</td>
</tr>
<tr>
<td>Bihar + Jharkhand</td>
<td>720</td>
<td>1440</td>
<td>1440</td>
<td>3600</td>
<td>1080</td>
<td>2880</td>
</tr>
<tr>
<td>Jharkhand</td>
<td>450</td>
<td>900</td>
<td>900</td>
<td>2250</td>
<td>675</td>
<td>1800</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Combined Rate</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Eastern &amp; Central U.P.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Varanasi, Allahabad, Gorakhpur, Kanpur, &amp; Lucknow</td>
<td>1170</td>
<td>2340</td>
<td>2340</td>
<td>5850</td>
<td>1755</td>
<td>4680</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Western &amp; Central U.P.</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Agra, Bareily, Kanpur+ Lucknow</td>
<td>900</td>
<td>1800</td>
<td>1800</td>
<td>4500</td>
<td>1350</td>
<td>3600</td>
</tr>
<tr>
<td>Varasani + Allahabad + Gorakpur</td>
<td>720</td>
<td>1440</td>
<td>1440</td>
<td>3600</td>
<td>1080</td>
<td>2880</td>
</tr>
<tr>
<td>Varanasi + Kanpur+ Lucknow</td>
<td>1080</td>
<td>2160</td>
<td>2160</td>
<td>5400</td>
<td>1620</td>
<td>4320</td>
</tr>
<tr>
<td>Varanasi + Kanpur</td>
<td>990</td>
<td>1980</td>
<td>1980</td>
<td>4950</td>
<td>1485</td>
<td>3960</td>
</tr>
<tr>
<td>Varanasi + Lucknow</td>
<td>810</td>
<td>1620</td>
<td>1620</td>
<td>4050</td>
<td>1215</td>
<td>3240</td>
</tr>
<tr>
<td>Kanpur + Lucknow</td>
<td>810</td>
<td>1620</td>
<td>1620</td>
<td>4050</td>
<td>1215</td>
<td>3240</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Western U.P. + Uttarkhand</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Agra + Breilly + Haldwani</td>
<td>504</td>
<td>1008</td>
<td>1008</td>
<td>2520</td>
<td>756</td>
<td>2016</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Capital Edition</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Lucknow + Patna + Ranchi</td>
<td>990</td>
<td>1980</td>
<td>1980</td>
<td>4950</td>
<td>1485</td>
<td>3960</td>
</tr>
<tr>
<td>Varanasi + Kanpur+ Lucknow+Patna+ Ranchi</td>
<td>1170</td>
<td>2340</td>
<td>2340</td>
<td>5850</td>
<td>1755</td>
<td>4680</td>
</tr>
</tbody>
</table> -->
                   <!-- <h2>Check out<strong> The Hindu</strong> Display  <strong>Ad Rates</strong></h2>
                    <p class="green-bg-para text-center">Tariff Rates in Rupees per Sq.cm. (w.e.f 1-05-2018)</p>
                    <div class="resp-table">
                        <table>
                            <thead>
                                <tr>
                                    <td>Edition</td>
                                    <td>Base</td>
                                    <td>Mon to Thus</td>
                                    <td>Fri &amp; Sat</td>
                                    <td>Sunday</td>
                                    <td>Front Page</td>
                                    <td>Page 3</td>
                                    <td>Back Page</td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Eastern Edition</td>
                                    <td></td>
                                    <td>220</td>
                                    <td>240</td>
                                    <td>230</td>
                                    <td>60</td>
                                    <td></td>
                                    <td></td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->




<script type="text/javascript">
    $('table').addClass('table table-striped bg-white text-dark shadow border rounded bg-success ');
    $('h2').addClass('text-center');
    $('table thead tr td').addClass('text-white mt-1 bg-secondary');
</script>
{% endblock %}

rates/templates/rates/paper-list.html
{% extends "main.html" %}
{% block content %}
<div class="container">
	<h3 class="text-center mb-2">List Of News Papers</h3>
	<br>
	<div class="row  mx-auto">
		{% for c in city %}
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c1" class="list-group text-center">
				<li class="my-2"><a href="{% url 'rates:news_ratess' pk=c.pk %}">{{c}}</a></li>
			</ul>
		</div>
		{% endfor %}
		<!-- <div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c2" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div>
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c3" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div>
		<div class="col-lg-3 col-md-4 col-sm-6 col-xsm-6">
			<ul id="c4" class="list-group text-center">
				<li class="my-2"></li>
			</ul>
		</div> -->
	<!-- </div>
</div>
<script type="text/javascript">
	for (var i = 1; i <= 122; i++) {
		var c = parseInt(i/30) + 1 ;
		$('#c'+c).append('<li class="my-2">NewsPaper '+i+'</li>');
	}
	//$('c1,c2,c3,c4').css({"font-size":"30px"})
</script> -->

{% endblock %}