mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',  auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('', views.TestPage.as_view(), name="test"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('',include('newspapers.urls', namespace="newspapers")),
    path('',include('rates.urls', namespace="rates")),
    #path('test/', views.TestPage.as_view(), name="test"),
    #path('newsletter/',include('newsletter.urls', namespace="newsletter")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newspapers/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='newspapers'

urlpatterns = [

			path('news/',views.NewsListView.as_view(),name='news_list'),
			path('news/<int:pk>/',views.NewsDetailView.as_view(),name='news_detail'),
			path('newspaper/', views.NewspaperListView.as_view(), name="newspaper_list"),
			path('newspaper/<int:pk>/', views.news_detail_view, name="newspaper_detail"),
			path('news/preriority',views.vader_sentiment,name='vader_sentiment'),
			path('train_delay/', views.train_delay, name="train_delay"),
			path('news/latest',views.latest_news,name='latest'),
			path('train_delay_stat/', views.train_delay_stat, name="train_delay_stat"),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rates/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='rates'

urlpatterns = [
	        path('news_ratess/<int:pk>/', views.news_ratess, name="news_ratess"),
	        path('news_rates/', views.news_rates, name="news_rates"),
	        path('city_rates/', views.city_rates, name="city_rates"),
	        path('paper_rates/<int:pk>/', views.paper_rates, name="paper_rates"),
	        path('calc/', views.calc, name="calc"),
            
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspapers/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Preference(models.Model):
    region = (('N', 'National'),('S', 'State'),('C', 'City'))
    preference_name = models.CharField(
        max_length=1,
        choices= region,
        blank=True,
        default='N',
    )

    def __str__(self):
        return self.preference_name

class Newspaper_name(models.Model):
    preference =models.ForeignKey('Preference',on_delete=models.CASCADE,default="")
    name= models.CharField(max_length=400)
    unique_id =models.IntegerField(blank=True,null=True)

    def __str__(self):
        return self.name

class News(models.Model):
    heading = models.CharField(max_length=400)
    article = models.TextField()
    published_date =models.DateTimeField(blank=True,null=True)
    unique_id =models.IntegerField(blank=True,null=True)
    newspaper_name= models.ForeignKey(Newspaper_name,related_name='related_news',on_delete=models.CASCADE)

    def __str__(self):
        return self.heading

rates/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from newspapers.models import Newspaper_name,Preference

class News_rates(models.Model):
	newspaper_name=models.OneToOneField(Newspaper_name, on_delete=models.CASCADE)
	rate_text=models.TextField(null=True, blank=True)
	preferences=models.OneToOneField(Preference, on_delete=models.CASCADE)
class City(models.Model):
	city_text=models.TextField(null=True, blank=True)

rates/views.py
from django.shortcuts import render
from .models import *
from newspapers.models import Newspaper_name
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse ,HttpResponseRedirect

# Create your views here.

# class ViewListView(ListView):
# 	model = News_rates
# 	context_object_name = 'news_rates'

# class ViewDetailView(DetailView):
# 	model = News_rates
# 	context_object_name = 'news_rates_detail'
# 	template_name = 'newspapers/news_rates_detail.html'

def news_rates(request):
	if request.method == 'POST':
		quote = request.POST.get('name')
		if not(quote):
			p=News_rates.objects.all()
			page = request.GET.get('page', 1)
			paginator = Paginator(p, 1)
			try:
				rrates = paginator.page(page)
			except PageNotAnInteger:
				rrates = paginator.page(1)
			except EmptyPage:
				rrates = paginator.page(paginator.num_pages)
			context ={
			'newspapers':Newspaper_name.objects.all(),
			'news_rates':rrates
			}
		else:
			# quote=Newspaper_name.objects.filter(name=quote1)
			p=list(News_rates.objects.filter(newspaper_name_id=int(quote[-1])))
			#print(p.rate_text)
			page = request.GET.get('page', 1)
			paginator = Paginator(p, 1)
			try:
				rrates = paginator.page(page)
			except PageNotAnInteger:
				rrates = paginator.page(1)
			except EmptyPage:
				rrates = paginator.page(paginator.num_pages)
			context ={
			'newspapers':Newspaper_name.objects.all(),
			'news_rates':rrates
			}
	else:
		p=News_rates.objects.all()
		#print(p.rate_text)
		page = request.GET.get('page', 1)
		paginator = Paginator(p, 1)
		try:
			rrates = paginator.page(page)
		except PageNotAnInteger:
			rrates = paginator.page(1)
		except EmptyPage:
			rrates = paginator.page(paginator.num_pages)
		context ={
		'newspapers':Newspaper_name.objects.all(),
		'news_rates':rrates
		}

	# context={
	# 'newspapers':Newspaper_name.objects.all()
	# }

	return render(request, 'rates/news_rate_detail.html', context=context )

def news_ratess(request,pk):
	context ={
		'newspapers':Newspaper_name.objects.all(),
		'news_rates':list(News_rates.objects.filter(newspaper_name_id=int(pk)))
	}
	return render(request, 'rates/news_rate_detail.html', context=context )


def paper_rates(request,pk):

	name=str(City.objects.get(pk=pk).city_text)
	print(name)

	from bs4 import BeautifulSoup
	from urllib.request import urlopen

	url ='https://www.bhavesads.com/'+name+'-newspaper/display-ad-rates'

	source = urlopen(url)
	html_data = BeautifulSoup(source).find('div',class_='tab-content').find('div',{'id': 'Categorys'}).find_all('div', class_='col-sm-12')
	paper=[]
	for data in html_data:
		try:
			paper1 = data.find('p',class_='special-text').text[:-10]
			paper.append(paper1)
		except AttributeError:
			pass

	names=[]
	for p in paper:
		names.append(Newspaper_name.objects.get(name=p))

	return render(request, 'rates/paper-list.html',{'city':names})


def city_rates(request):
	return render(request, 'rates/city-list.html',{'city':City.objects.all()})

def calc(request):

	return render(request, 'rates/calculater.html', {})

newspapers/templates/newspapers/latest.html
{% extends "main.html" %}
{% block content %}
<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>


                <div class="container row mx-auto">
                    <div class="col-12 my-2 border bg-white text-dark rounded">
                        <h4 class="text-center d-block my-3">Popular News From "NewsPaper Name"</h4>
                    </div>

                    <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                      {% for single_news in news %}
                        <h4 class="ml-1 d-block my-3">{{single_news.heading}}</h4>
                        <P class="container">{{single_news.article}}</P>
                      {% endfor %}
                    </div>
                </div>
{% endblock %}

newspapers/templates/newspapers/news.html
 {% extends "main.html" %}

                {% block content %}

<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>
<div class="container mx-auto">
    <h5 class="text-center">Fetched News</h5>
    <form class="form-inline" method="post" action="action-url">
        <div class="col-lg-3 mt-3">
            <select class="form-control-sm bg-dark text-white col-12 border-success" id="sel1">
                <option>Select</option>
                <option>Favorates</option>
                <option>Latest</option>
            </select>
        </div>
        <div class="text-center" id="pp">
            <input class="btn btn-sm btn-success  col-12 mt-3" type="submit" name="" value="Search News">
        </div>
        <script type="text/javascript">
            if($(window).width()<596)
                $('#pp').addClass('mx-auto');
            console.log(5);
        </script>
    </form>
</div>

                <div class="row rounded mx-auto container">
                    <div class="col-12 mt-5 jumbotron img-jumbo" >
                        <br><br><br><br><br>
                    </div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 text-justify bg-white text-dark border rounded">
                        <h4 class="ml-1 d-block my-3 text-center">{{news_detail.heading}}</h4>
                        <P class="container">{{news_detail.article}}</P>
                        <div class="bg-white my-3 mx-2">
                            <a href="#" id="like" onclick="likeit();"><i class="fas fa-star fa-2x text-info mx-2" ></i></a>
                            <!-- <a href="#"<i class="fas fa-star fa-2x text-info mx-2"></i></a> -->
                            <a href="#" data-target="#share-modal" data-toggle="modal"><i class="fas fa-share-alt fa-2x text-info mx-2"></i></a>
                        </div>
                        <script type="text/javascript">
                            like = 0;
                            function likeit(){
                                a = $('#like');
                                if(like==0) {
                                    a.html('<i class="fas fa-star fa-2x text-info mx-2">');
                                    like = 1;
                                }
                                else{
                                    a.html('<i class="far fa-star fa-2x text-info mx-2">');
                                    like = 0;
                                }
                            }
                        </script>
                    </div>
                </div>


            <div class="modal fade" id="share-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="text-primary"> Share on social media </h5>
                            <button class="close" data-dismiss="modal"> &times; </button>
                        </div>
                        <div class="modal-body mx-auto my-3">
                            <ul class="list-inline">
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-secondary text-center"><a class="text-white" href="https://www.facebook.com/sharer.php?u=url-here" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-info text-center"><a class="text-white" href="https://twitter.com/intent/tweet?text=url-here" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-success text-center">
                                        <a class="text-white" href="https://api.whatsapp.com/send?text=url-here" target="_blank">
                                            <i class="fab fa-whatsapp fa-2x"></i>
                                        </a>
                                    </div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-danger text-center"><a class="text-white" href="https://plus.google.com/share?url=url-here" target="_blank"><i class="fab fa-google-plus-g fa-2x"></i></a></div>
                                </li>
                            </ul><br>
                            <input type="checkbox" id="ch" onchange="_toggler(this)"><h4 class="text-center">Share Custome News</h4><br>
                            <div class="border">
                                <textarea class="form-control" rows="5" placeholder="have a manual news url? type Here and click on any above social media button" disabled></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                function _toggler(a){
                    if(a.checked) $('textarea').prop('disabled',false);
                    else $('textarea').prop('disabled',true);
                }
                function isMobile() {
                  try{ document.createEvent("TouchEvent"); return true; }
                  catch(e){ return false; }
                }
                function doshare(api){
                    var x = $('textarea').val();
                    if($('#ch').is(":checked")) flag = 1;
                    else flag = 0;
                    curl = window.location.href;
                    if(!isMobile() && api.includes('whatsapp'))
                        alert('Share on whatsapp is availble only on mobile Devices.');
                    else if(isMobile()){
                        if(flag)
                           window.location.href = api+x;
                        else 
                           window.location.href = api+curl;
                    }
                    else{
                        if(flag)
                            window.open(api+x);
                        else 
                           window.open(api+curl);
                    }
                }
                $('.div-circle').css({"width":"45px","height":"45px","border-radius":"50%","line-height":"55px"});
            </script>

            {% endblock %}

newspapers/templates/newspapers/news00.html
 {% extends "main.html" %}

                {% block content %}

<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>
<div class="container mx-auto">
    <h5 class="text-center">Fetched News</h5>
    <form class="form-inline" method="post" action="action-url">
        <div class="col-lg-3 mt-3">
            <select class="form-control-sm bg-dark text-white col-12 border-success" id="sel1">
                <option>Select</option>
                <option>Favorates</option>
                <option>Latest</option>
            </select>
        </div>
        <div class="text-center" id="pp">
            <input class="btn btn-sm btn-success  col-12 mt-3" type="submit" name="" value="Search News">
        </div>
        <script type="text/javascript">
            if($(window).width()<596)
                $('#pp').addClass('mx-auto');
            console.log(5);
        </script>
    </form>
</div>

                <div class="row rounded mx-auto container">
                    <div class="col-12 mt-5 jumbotron img-jumbo" >
                        <br><br><br><br><br>
                    </div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 text-justify bg-white text-dark border rounded">
                        <h4 class="ml-1 d-block my-3 text-center">{{news_detail.heading}}</h4>
                        <P class="container">{{news_detail.article}}</P>
                        <div class="bg-white my-3 mx-2">
                            <span href="" id="like" onclick="likeit();"><i class="fas fa-star fa-2x text-info mx-2" ></i></span>
                            <!-- <a href="#"<i class="fas fa-star fa-2x text-info mx-2"></i></a> -->
                            <button class="btn btn-danger m-auto d-block" data-target="#share-modal" data-toggle="modal"><i class="fas fa-share-alt fa-2x text-info mx-2"></i></button>
                        </div>
                        <script type="text/javascript">
                            like = 0;
                            function likeit(){
                                a = $('#like');
                                if(like==0) {
                                    a.html('<i class="fas fa-star fa-2x text-info mx-2">');
                                    like = 1;
                                }
                                else{
                                    a.html('<i class="far fa-star fa-2x text-info mx-2">');
                                    like = 0;
                                }
                            }
                        </script>
                    </div>
                </div>

            
            <div class="modal fade" id="share-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="text-primary"> Share on social media </h5>
                            <button class="close" data-dismiss="modal"> &times; </button>
                        </div>
                        <div class="modal-body mx-auto my-3">
                            <ul class="list-inline">
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-secondary text-center"><a class="text-white" href="https://www.facebook.com/sharer.php?u=url-here" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-info text-center"><a class="text-white" href="https://twitter.com/intent/tweet?text=url-here" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-success text-center">
                                        <a class="text-white" href="https://api.whatsapp.com/send?text=url-here" target="_blank">
                                            <i class="fab fa-whatsapp fa-2x"></i>
                                        </a>
                                    </div>
                                </li>
                                <li class="list-inline-item mx-3">
                                    <div class="div-circle bg-danger text-center"><a class="text-white" href="https://plus.google.com/share?url=url-here" target="_blank"><i class="fab fa-google-plus-g fa-2x"></i></a></div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('.div-circle').css({"width":"45px","height":"45px","border-radius":"50%","line-height":"55px"});
            </script>

            {% endblock %}

newspapers/templates/newspapers/newspaper.html
{% extends "main.html" %}

                {% block content %}
<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>
<div class="container mx-auto mb-4">
    <h5 class="text-center">Search For Newspaper</h5>
    <form class="form-inline" method="post" action="action-url">
        <div class="col-lg-3 mt-3">
            <select class="form-control-sm bg-dark text-white col-12 border-success" id="sel1">
                <option>Select</option>
                <option>1</option>
                <option>2</option>
            </select>
        </div>
        <div class="text-center" id="pp">
            <input class="btn btn-sm btn-success  col-12 mt-3" type="submit" name="" value="Search Newspaper">
        </div>
        <script type="text/javascript">
            if($(window).width()<596)
                $('#pp').addClass('mx-auto');
            console.log(5);
        </script>
    </form>
</div>

                <div class="row rounded mx-auto container">
                   	<div class="col-12 mt-5 jumbotron img-jumbo" >
        				<br><br><br><br><br>
        			</div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 my-2 border bg-white text-dark rounded">
                        <h4 class="text-center d-block my-3">Latest News From "{{newspaper_detail.name}}"</h4>
                    </div>
                    {% for new in newspaper_detail.Newspaper.heading %}
                    <div class="col-12 text-justify bg-white text-dark border rounded">
                        <h4 class="ml-1 d-block my-3"{{new.heading}}</h4>
                        <P class="container">{{new.heading}}</P>
                        <a href="{% url 'newspapers:news_detail' pk=News.pk %}" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 2</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="{% url 'newspapers:news_detail' pk=News.pk %}}" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 3</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div> -->
                </div> 
            {% endblock %}

newspapers/templates/newspapers/newspaper_detail.html
{% extends "main.html" %}

                {% block content %}
<div id="tog" class="text-white" style="position: absolute;z-index: 10;">
    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
</div>
<div class="container mx-auto mb-4">
    <h5 class="text-center">Search For Newspaper</h5>
    <form class="form-inline" method="get" action="#" >
        {% csrf_token %}
        <div class="col-lg-3 mt-3">
            <select class="form-control-sm bg-dark text-white col-12 border-success" id="sel1">
                <option>Select</option>
                {% for opt in names %}
                <option>{{opt.name}}</option>
                
                <!-- <option>2</option> -->
                {% endfor %}
            </select>
        </div>
        <div class="text-center" id="pp">
            <input class="btn btn-sm btn-success  col-12 mt-3" type="submit" name="" value="Search Newspaper">
        </div>
        <script type="text/javascript">
            if($(window).width()<596)
                $('#pp').addClass('mx-auto');
            console.log(5);
        </script>
    </form>
</div>

                <div class="row rounded mx-auto container">
                   	<div class="col-12 mt-5 jumbotron img-jumbo" >
        				<br><br><br><br><br>
        			</div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 my-2 border bg-white text-dark rounded">
                        <h4 class="text-center d-block my-3">Latest News From
                         {% for opt in newspaper %}
                            {{opt.name}}
                <!-- <option>2</option> -->
                            {% endfor %}
                     </h4>
                    </div>
                    {% for new in news %}
                    <div class="col-12 text-justify bg-white text-dark border rounded mt-2">
                        <h4 class="ml-1 d-block my-3">{{new.heading}}</h4>
                        <P class="container">{{new.article|truncatechars:"50"}}</P>
                        <a href="{% url 'newspapers:news_detail' pk=new.pk %}" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>

                    </div>
                    
                    {% endfor %}
                    <!-- <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 2</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 3</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div> -->
                </div> 
            {% endblock %}

newspapers/templates/newspapers/newspaper_detail0.html
{% extends "main.html" %}

                {% block content %}
                <div id="tog" class="" style="position: absolute;z-index: 10;">
                    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
                </div>
                <div class="row rounded mx-auto container">
                   	<div class="col-12 mt-5 jumbotron img-jumbo" >
        				<br><br><br><br><br>
        			</div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 my-2 border bg-white text-dark rounded">
                        <h4 class="text-center d-block my-3">Latest News From {{newspaper_detail.name}}</h4>
                    </div>
                    {% for new in newspaper_detail.Newspaper.heading %}
                    
                    <div class="col-12 text-justify bg-white text-dark border rounded">
                        <h4 class="ml-1 d-block my-3">{{new.heading}}</h4>
                        <P class="container">{{new.heading}}
                        <a href="{% url 'newspapers:news_detail' pk=News.pk %}}" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 2</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 3</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div> -->
                </div>
                {% endblock %}
            

newspapers/templates/newspapers/newspaper_detail00.html
{% extends "main.html" %}

                {% block content %}
                <div id="tog" class="" style="position: absolute;z-index: 10;">
                    <span class="btn btn-sm" data-toggle="offcanvas"><i class="fas fa-bars fa-2x"></i></span>
                </div>
                <div class="row rounded mx-auto container">
                   	<div class="col-12 mt-5 jumbotron img-jumbo" >
        				<br><br><br><br><br>
        			</div>
                </div>
                <div class="container row mx-auto">
                    <div class="col-12 my-2 border bg-white text-dark rounded">
                        <h4 class="text-center d-block my-3">Latest News From {{newspaper_detail.name}}</h4>
                    </div>
                    {% for new in newspaper_detail.Newspaper.heading %}
                    
                    <div class="col-12 text-justify bg-white text-dark border rounded">
                        <h4 class="ml-1 d-block my-3">{{new.heading}}</h4>
                        <P class="container">{{new.heading}}
                        <a href="{% url 'newspapers:news_detail' pk=News.pk %}}" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    {% endfor %}
                    <!-- <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 2</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div>
                    <div class="col-12 text-justify bg-white text-dark border rounded mt-1">
                        <h4 class="ml-1 d-block my-3">News 3</h4>
                        <P class="container">Short Description Of News. Lorem Ipsum is simply dummy text of the printing and typesetting industry......</P>
                        <a href="/url-of-news/" class="d-inline-block mb-2 btn btn-outline-info float-right">Read More...</a>
                    </div> -->
                </div>
                {% endblock %}
            